# Generated by Django 5.1.4 on 2025-02-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('skills_expertise', models.CharField(blank=True, max_length=50, null=True)),
                ('portfolio_link', models.CharField(blank=True, max_length=50, null=True)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='freelancer_id_proofs')),
                ('registered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_verified', models.CharField(blank=True, default='pending', max_length=50, null=True)),
            ],
        ),
    ]
