# Generated by Django 5.1.4 on 2025-02-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Freelancer',
            new_name='FreelancerDb',
        ),
    ]
