# Generated by Django 5.1.4 on 2025-02-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0002_rename_freelancer_freelancerdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerdb',
            name='password',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
    ]
