# Generated by Django 5.1.4 on 2025-02-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0003_alter_freelancerdb_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, default='pending', max_length=50, null=True)),
                ('usertype', models.CharField(blank=True, default='pending', max_length=50, null=True)),
            ],
        ),
    ]
