# Generated by Django 5.1.4 on 2025-02-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0004_logindb'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerdb',
            name='login',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
