# Generated by Django 5.1.4 on 2025-02-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0005_freelancerdb_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerprofileDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('social_media_link', models.CharField(blank=True, max_length=100, null=True)),
                ('per_hour_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('availability', models.CharField(blank=True, max_length=20, null=True)),
                ('experience_level', models.CharField(blank=True, max_length=20, null=True)),
                ('languages_known', models.CharField(blank=True, max_length=100, null=True)),
                ('about_me', models.CharField(blank=True, max_length=100, null=True)),
                ('lid', models.CharField(max_length=50)),
            ],
        ),
    ]
