# Generated by Django 5.1.4 on 2025-02-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0006_freelancerprofiledb'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerServiceDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('freelancer_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
