# Generated by Django 5.1.4 on 2025-02-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0007_freelancerservicedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerservicedb',
            name='category',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
