# Generated by Django 5.1.4 on 2025-02-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0008_alter_freelancerservicedb_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerservicedb',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
