# Generated by Django 5.1.4 on 2025-02-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0009_alter_freelancerservicedb_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email_address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('photo', models.FileField(blank=True, null=True, upload_to='clients')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('company_type', models.CharField(blank=True, max_length=100, null=True)),
                ('project_needs', models.TextField(blank=True, null=True)),
                ('company_website', models.CharField(blank=True, max_length=200, null=True)),
                ('business_verification_document', models.FileField(blank=True, null=True, upload_to='verification_documents')),
            ],
        ),
    ]
