# Generated by Django 5.1.4 on 2025-02-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0010_clientdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdb',
            name='photo',
        ),
        migrations.AlterField(
            model_name='clientdb',
            name='password',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
