# Generated by Django 5.1.4 on 2025-02-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0011_remove_clientdb_photo_alter_clientdb_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdb',
            name='login',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
