# Generated by Django 5.1.4 on 2025-02-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0012_clientdb_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPostDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('budget_type', models.CharField(blank=True, max_length=20, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('required_skills', models.CharField(blank=True, max_length=255, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='project_files')),
                ('visibility', models.CharField(default='public', max_length=10)),
                ('client_id', models.IntegerField(max_length=50)),
            ],
        ),
    ]
