# Generated by Django 5.1.4 on 2025-02-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0013_projectpostdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpostdb',
            name='client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
