# Generated by Django 5.1.4 on 2025-02-24 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0014_alter_projectpostdb_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpostdb',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
