# Generated by Django 5.1.4 on 2025-02-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0016_projectlike'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectLike',
            new_name='ProjectLikeDb',
        ),
    ]
