# Generated by Django 5.1.4 on 2025-02-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0017_rename_projectlike_projectlikedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlikedb',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
