# Generated by Django 5.1.4 on 2025-02-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0018_alter_projectlikedb_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('freelancer_id', models.IntegerField(blank=True, null=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('proposed_budget', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_time', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
