# Generated by Django 5.1.4 on 2025-02-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0019_proposaldb'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProjectDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('freelancer_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
