# Generated by Django 5.2.3 on 2025-07-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0020_savedprojectdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer', models.IntegerField(blank=True, null=True)),
                ('what_i_do', models.CharField(max_length=500)),
                ('why_i_choose', models.CharField(max_length=500)),
            ],
        ),
    ]
