# Generated by Django 5.2.3 on 2025-07-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0021_profileentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer', models.IntegerField(blank=True, null=True)),
                ('project_name', models.CharField(max_length=100)),
                ('tools_used', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
