# Generated by Django 5.2.3 on 2025-07-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0022_portfolioproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='portfolio'),
        ),
    ]
